# Generated by Django 6.0.6 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('stars', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
